export const icons = {
  addPostIcon: '/icons/add-post-icon.svg',
  bloggerPostsIcon: '/icons/blogger-posts-icon.svg',
  editPostIcon: '/icons/edit-post-icon.svg',
  excludePostIcon: '/icons/exclude-post-icon.svg',
  favoritePostIcon: '/icons/favorite-post-icon.svg',
  favoritePostsMenuIcon: '/icons/favorite-posts-menu-icon.svg',
  favoritesPostsIcon: '/icons/favorites-posts-icon.svg',
  greenLogoIcon: '/icons/green-logo-icon.svg',
  logoutIcon: '/icons/logout-icon.svg',
  logoutMenuIcon: '/icons/logout-menu-icon.svg',
  nextPrevArrowIcon: '/icons/next-prev-arrow-icon.svg',
  openMenuGreenIcon: '/icons/open-menu-green-icon.svg',
  openMenuRedIcon: '/icons/open-menu-red-icon.svg',
  pagesArrowIcon: '/icons/pages-arrow-icon.svg',
  profileIcon: '/icons/profile-icon.svg',
  redLogoIcon: '/icons/red-logo-icon.svg',
  searchWhiteIcon: '/icons/search-white-icon.svg',
  searchGrayIcon: '/icons/search-gray-icon.svg',
  unfavoritePostIcon: '/icons/unfavorite-post-icon.svg',
} as const;

export const images = {
  gallery1Image: '/images/gallery1.jpg',
  gallery2Image: '/images/gallery2.jpg',
  gallery3Image: '/images/gallery3.jpg',
  gallery4Image: '/images/gallery4.jpg',
  gallery5Image: '/images/gallery5.jpg',
  gallery6Image: '/images/gallery6.jpg',
  homeImage: '/images/home.jpg',
  newsTest1Image: '/images/news-test1.jpg',
  newsTest2Image: '/images/news-test2.jpg',
  userTest1Image: '/images/user-test1.jpg',
  userTest2Image: '/images/user-test2.jpg',
} as const;
